config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :services
    resources :announcements
    resources :notifications
    resources :users
    namespace :active_storage do
      resources :variant_records
    end
    namespace :active_storage do
      resources :blobs
    end
    namespace :active_storage do
      resources :attachments
    end
    root to: "dashboard#show"
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  resources :forum_threads do
    resources :forum_posts, module: :forum_threads
  end
  
  root to: 'forum_threads#index'
end

app/models/forum_thread.rb
# == Schema Information
#
# Table name: forum_threads
#
#  id         :bigint           not null, primary key
#  subject    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
class ForumThread < ApplicationRecord
    belongs_to :user
    has_many :forum_posts
    has_many :users, through: :forum_posts

    accepts_nested_attributes_for :forum_posts

    validates :subject, presence: true
    validates_associated :forum_posts
end

app/controllers/forum_threads/forum_posts_controller.rb
class ForumThreads::ForumPostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_forum_thread

    def create
        @forum_post = @forum_thread.forum_posts.new forum_post_params
        @forum_post.user = current_user

        if @forum_post.save
            @forum_post.send_notifications!
            redirect_to forum_thread_path(@forum_thread, anchor: "forum_post_#{@forum_post.id}"), notice: "Successfully posted!"
        else
            redirect_to @forum_thread, alert: "Unable to save your post"
        end
    end

    private

    def set_forum_thread
        @forum_thread = ForumThread.find(params[:forum_thread_id])
    end

    def forum_post_params
        params.require(:forum_post).permit(:body)
    end

end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_forum_thread, except: [:index, :new, :create]

    def index
        @q = ForumThread.search(params[:q])
        @forum_threads = @q.result(distinct: true)
    end

    def show
        @forum_post = ForumPost.new
    end

    def new
        @forum_thread = ForumThread.new
        @forum_thread.forum_posts.new
    end

    def create
        @forum_thread = current_user.forum_threads.new forum_thread_params
        @forum_thread.forum_posts.first.user_id = current_user.id

        if @forum_thread.save
            redirect_to @forum_thread
        else
            render action: :new
        end
    end

    private

    def set_forum_thread
        @forum_thread = ForumThread.find(params[:id])
    end

    def forum_thread_params
        params.require(:forum_thread).permit(:subject, forum_posts_attributes: [:body])
    end

end

app/views/forum_threads/_forum.html.erb
<%= form_for @forum_thread do |f| %>
    <div class="form-group">
        <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>

    <%= f.fields_for :forum_posts do |p| %>
        <div class="form-group">
            <%= p.text_area :body, placeholder: "Add a comment", rows: 10, class: "form-control" %>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
    </div>
<% end %>

app/views/forum_threads/_forum_thread.html.erb
<%= link_to forum_thread do %>
    <h3><%= forum_thread.subject %></h3>
<% end %>

app/views/forum_threads/index.html.erb
<div class="container">
    <div class="pull-right">
        <%= link_to "New Thread", new_forum_thread_path, class: "btn btn-success" %>
    </div>
    <div class="pull-right" style="margin-right: 10px">
        <%= search_form_for @q, html: { class: "form-inline" } do |f| %>
            <%= f.search_field :subject_or_forum_posts_body_cont, placeholder: "Search...", class: "form-control" %>
        <% end %>
    </div>

    <h1 class="page-header">Forum Threads</h1>
    <%= render @forum_threads %>
</div>

app/views/forum_threads/new.html.erb
<h1>New Thread</h1>

<%= render "forum" %>

app/views/forum_threads/show.html.erb
<div class="container">
    <h1><%= @forum_thread.subject %></h1>
    <p class="text-muted">Created by <%= @forum_thread.user.name %></p>
    <%= render @forum_thread.forum_posts %>

    <hr />
    <%= render partial: "forum_posts/form" %>
</div>